// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetHandler() {
  return window['go']['main']['App']['AssetHandler']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetReaderManifest(arg1) {
  return window['go']['main']['App']['GetReaderManifest'](arg1);
}

export function GetReaderProgress(arg1) {
  return window['go']['main']['App']['GetReaderProgress'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListLibraryManga() {
  return window['go']['main']['App']['ListLibraryManga']();
}

export function UpdateReaderProgress(arg1) {
  return window['go']['main']['App']['UpdateReaderProgress'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
