// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrarySource(arg1) {
  return window['go']['main']['App']['AddLibrarySource'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearThumbnailCache() {
  return window['go']['main']['App']['ClearThumbnailCache']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetReaderManifest(arg1) {
  return window['go']['main']['App']['GetReaderManifest'](arg1);
}

export function GetReaderProgress(arg1) {
  return window['go']['main']['App']['GetReaderProgress'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetThumbnailCacheSize() {
  return window['go']['main']['App']['GetThumbnailCacheSize']();
}

export function ListLibraryManga() {
  return window['go']['main']['App']['ListLibraryManga']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RelocateLibrarySource(arg1, arg2) {
  return window['go']['main']['App']['RelocateLibrarySource'](arg1, arg2);
}

export function RemoveLibrarySource(arg1) {
  return window['go']['main']['App']['RemoveLibrarySource'](arg1);
}

export function RescanSource(arg1) {
  return window['go']['main']['App']['RescanSource'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleCollection(arg1) {
  return window['go']['main']['App']['ToggleCollection'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function UpdateLibrarySource(arg1) {
  return window['go']['main']['App']['UpdateLibrarySource'](arg1);
}

export function UpdateReaderProgress(arg1) {
  return window['go']['main']['App']['UpdateReaderProgress'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
