// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {contracts} from '../models';

export function AssetHandler():Promise<http.Handler>;

export function GetAppVersion():Promise<string>;

export function GetReaderManifest(arg1:string):Promise<contracts.ReaderManifest>;

export function GetReaderProgress(arg1:string):Promise<contracts.ReaderProgress>;

export function GetSettings():Promise<contracts.AppSettings>;

export function ListLibraryManga():Promise<Array<contracts.LibraryManga>>;

export function SelectDirectory():Promise<string>;

export function UpdateReaderProgress(arg1:contracts.ReaderProgress):Promise<contracts.ReaderProgress>;

export function UpdateSettings(arg1:contracts.AppSettings):Promise<contracts.AppSettings>;
