// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function AddLibrarySource(arg1:contracts.LibrarySource):Promise<contracts.AppSettings>;

export function CheckForUpdates():Promise<contracts.UpdateCheckResult>;

export function ClearThumbnailCache():Promise<void>;

export function GetAppVersion():Promise<contracts.AppVersionInfo>;

export function GetReaderManifest(arg1:string):Promise<contracts.ReaderManifest>;

export function GetReaderProgress(arg1:string):Promise<contracts.ReaderProgress>;

export function GetSettings():Promise<contracts.AppSettings>;

export function GetThumbnailCacheSize():Promise<number>;

export function ListLibraryManga():Promise<Array<contracts.LibraryManga>>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RelocateLibrarySource(arg1:string,arg2:string):Promise<contracts.AppSettings>;

export function RemoveLibrarySource(arg1:string):Promise<contracts.AppSettings>;

export function RescanSource(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ToggleCollection(arg1:string):Promise<boolean>;

export function TogglePin(arg1:string):Promise<boolean>;

export function UpdateLibrarySource(arg1:contracts.LibrarySource):Promise<contracts.AppSettings>;

export function UpdateReaderProgress(arg1:contracts.ReaderProgress):Promise<contracts.ReaderProgress>;

export function UpdateSettings(arg1:contracts.AppSettings):Promise<contracts.AppSettings>;
